### PR TITLE
[CI] Fixing minor issues in github actions

### LINKED ISSUE #584: [CI] failing git-init on kythe repo
After fixing #556, the next issue is related to Kythe as a dependency.

See this log:
https://travis-ci.org/github/google/verible/jobs/742535455

```
INFO: Repository io_kythe instantiated at:
  /src/verible/verible-v0.0-759-g7941857/WORKSPACE:143:15: in <toplevel>
Repository rule git_repository defined at:
  /root/.cache/bazel/_bazel_root/2ccca2c4c14abc5021f2a7b18d0dec9b/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
ERROR: An error occurred during the fetch of repository 'io_kythe':
   Traceback (most recent call last):
	File "/root/.cache/bazel/_bazel_root/2ccca2c4c14abc5021f2a7b18d0dec9b/external/bazel_tools/tools/build_defs/repo/git.bzl", line 181, column 30, in _git_repository_implementation
		update = _clone_or_update(ctx)
	File "/root/.cache/bazel/_bazel_root/2ccca2c4c14abc5021f2a7b18d0dec9b/external/bazel_tools/tools/build_defs/repo/git.bzl", line 36, column 20, in _clone_or_update
		git_ = git_repo(ctx, directory)
	File "/root/.cache/bazel/_bazel_root/2ccca2c4c14abc5021f2a7b18d0dec9b/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 91, column 12, in git_repo
		_update(ctx, git_repo)
	File "/root/.cache/bazel/_bazel_root/2ccca2c4c14abc5021f2a7b18d0dec9b/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 101, column 9, in _update
		init(ctx, git_repo)
	File "/root/.cache/bazel/_bazel_root/2ccca2c4c14abc5021f2a7b18d0dec9b/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 118, column 15, in init
		_error(ctx.name, cl, st.stderr)
	File "/root/.cache/bazel/_bazel_root/2ccca2c4c14abc5021f2a7b18d0dec9b/external/bazel_tools/tools/build_defs/repo/git_worker.bzl", line 190, column 9, in _error
		fail("error running '%s' while working with @%s:\n%s" % (command_text, name, stderr))
Error in fail: error running 'git init /root/.cache/bazel/_bazel_root/2ccca2c4c14abc5021f2a7b18d0dec9b/external/io_kythe' while working with @io_kythe:
src/main/tools/process-wrapper-legacy.cc:80: "execvp(git, ...)": No such file or directory
ERROR: no such package '@io_kythe//': error running 'git init /root/.cache/bazel/_bazel_root/2ccca2c4c14abc5021f2a7b18d0dec9b/external/io_kythe' while working with @io_kythe:
src/main/tools/process-wrapper-legacy.cc:80: "execvp(git, ...)": No such file or directory
INFO: Elapsed time: 7.206s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)
The command '/bin/sh -c bazel build --workspace_status_command=bazel/build-version.sh -c opt //...' returned a non-zero code: 1
The command "./.github/travis/script.sh" exited with 1.
```

FYI @ivan444 .

### PR DESCRIPTION
**Pull request by wtatarski**
Fixes #584 and other issue on github actions CI

### CODE REVIEW

**Comment by wtatarski** [comment]
It should be OK with tests on ubuntu. Centos 6 and 7 require fixes.
https://github.com/antmicro/verible/actions/runs/370782533

**Review by fangism — COMMENTED** [review]
@mithro does this conflict with your fixes in #608 ?

**Comment by mithro** [comment]
@wtatarski - Did you see my pull request at #608

**Comment by wtatarski** [comment]
@mithro 
Ok, I've seen it now. I see that most of the fixes are in your PR, so my is not really needed anymore.

**Pull request closed without merging**
