### PR TITLE
Adding missing unique0 case

### PR DESCRIPTION
**Pull request by AaronKel**
Fix for issue #125

### CODE REVIEW

**Comment by AaronKel** [comment]
@googlebot I fixed it.

**Comment by hzeller** [comment]
Hey @AaronKel could you sign the CLA and update the thread ?

**Comment by AaronKel** [comment]
> Hey @AaronKel could you sign the CLA and update the thread ?

Hi @hzeller I have already signed it, see: https://github.com/google/verible/pull/124#issuecomment-574408470

**Comment by hzeller** [comment]
I guess
@googlebot I fixed it.
needs to be said.

**Comment by AaronKel** [comment]
@hzeller I think it is complaining because of the root account that commited to my repository (which is me). Is it okay to merge this one and for future ones I'll configure the git

**Comment by AaronKel** [comment]
@googlebot I fixed it.

**Comment by AaronKel** [comment]
@googlebot I fixed it.

**Comment by AaronKel** [comment]
@googlebot I signed it!

**Comment by hzeller** [comment]
mmh, if it was the last commit, you could probably do some `git amend --author="..."` and force-push, but given that the root-submit is two submit ago that probably won't work.

Can you create a fresh Pull request and rebase your change with the correct author ?

Sorry about the inconvenience :/

**Pull request closed without merging**
