### PR TITLE
Reformulate unix-specific file operations with std::filesystem

### PR DESCRIPTION
**Pull request by hzeller**
Issues #307 #765

Signed-off-by: Henner Zeller <h.zeller@acm.org>

### CODE REVIEW

**Review by mithro — APPROVED** [review]

**Comment by mithro** [comment]
If CI says yes, go ahead.

**Comment by hzeller** [comment]
I might need some help with the `releasing/` stuff @mithro : the c++17 `<filesystem>` header is only available with gcc-8 (I think) onwards.
Can these compilers easily be installed/used in the release docker files ?

**Comment by hzeller** [comment]
CC: @corco once the issue with releasing on older platforms is resolved, this will bring a `file_util` that compile on windows (notice the windows CI passing, which now also includes the `file_util_test`).

So if you want to get unblocked until this pull request can be merged, feel free to add the changes to your local working branch for a new round of finding the next issues to tackle.

**Comment by corco** [comment]
@mithro @hzeller In the spirit of unblocking #307, I suggest to keep the old file separate and use it on non-Windows platform. Getting rid of the old file should be a separate issue (unless the fix is quick & easy of course). As much as I don't like having platform-specific files, it should be the only one to support Windows.

Something like this in the BUILD file:

```bazel
srcs = select({
        "@platforms//os:windows": ["file_util_c++17.cc"],
        "//conditions:default": ["file_util_unix.cc"],
    }),
```

**Comment by hzeller** [comment]
Another thing I considered was maybe using some compatibility header such as https://github.com/gulrak/filesystem

I plan to make it work to the end of this day whatever it takes. If in the next few hours it turns out the releases are a bit more work, I'll probably submit your suggestion @corco , then we have time to get it nice later.

**Comment by hzeller** [comment]
Alright @corco this is merged. So hopefully it helps in further unlocking more Windows tests.

**Pull request merged**
