### PR TITLE
travis: Compile against multiple compilers.

### PR DESCRIPTION
**Pull request by mithro**
* GCC 8
 * GCC 9
 * clang-8

Signed-off-by: Tim 'mithro' Ansell <me@mith.ro>

### CODE REVIEW

**Comment by hzeller** [comment]
It is probably sufficient to just test the gcc's for now. I think last time I tested with clang, the `m4` compilation used as part of the bison/lex bootstrapping process didn't work (we'll see when travis is ready)

**Comment by hzeller** [comment]
If the outputs of the failing tests are nicely visible in the output: LGTM

**Comment by mithro** [comment]
Two tests are failing on travis with gcc-7 it seems;
```
//common/strings:rebase_test                                             FAILED in 0.4s
  /home/travis/.cache/bazel/_bazel_travis/09cbf2eb38e4f867e4fa81d2eb791463/execroot/com_google_verible/bazel-out/k8-fastbuild/testlogs/common/strings/rebase_test/test.log
//common/text:token_info_test                                            FAILED in 0.3s
  /home/travis/.cache/bazel/_bazel_travis/09cbf2eb38e4f867e4fa81d2eb791463/execroot/com_google_verible/bazel-out/k8-fastbuild/testlogs/common/text/token_info_test/test.log
Executed 295 out of 295 tests: 293 tests pass and 2 fail locally.
There were tests whose specified size is too big. Use the --test_verbose_timeout_warnings command line option to see which ones these are.
The command "bazel test --noshow_progress --cxxopt='-std=c++17' //..." exited with 3.
```

**Comment by mithro** [comment]
```
./bazel-out/k8-fastbuild/testlogs/common/strings/rebase_test/test.log
--------------
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //common/strings:rebase_test
-----------------------------------------------------------------------------
Running main() from gmock_main.cc
[==========] Running 9 tests from 2 test suites.
[----------] Global test environment set-up.
[----------] 2 tests from RebaseStringViewDeathTest
[ RUN      ] RebaseStringViewDeathTest.SubstringMismatch
[       OK ] RebaseStringViewDeathTest.SubstringMismatch (188 ms)
[ RUN      ] RebaseStringViewDeathTest.SubstringMismatch2
[       OK ] RebaseStringViewDeathTest.SubstringMismatch2 (127 ms)
[----------] 2 tests from RebaseStringViewDeathTest (315 ms total)
[----------] 7 tests from RebaseStringViewTest
[ RUN      ] RebaseStringViewTest.EmptyStringsZeroOffset
common/strings/rebase_test.cc:35: Failure
Value of: BoundsEqual(text_view, substr_view)
  Actual: true
Expected: false
[  FAILED  ] RebaseStringViewTest.EmptyStringsZeroOffset (0 ms)
[ RUN      ] RebaseStringViewTest.IdenticalCopy
[       OK ] RebaseStringViewTest.IdenticalCopy (0 ms)
[ RUN      ] RebaseStringViewTest.NewSubstringNotAtFront
[       OK ] RebaseStringViewTest.NewSubstringNotAtFront (0 ms)
[ RUN      ] RebaseStringViewTest.UsingCharPointer
[       OK ] RebaseStringViewTest.UsingCharPointer (0 ms)
[ RUN      ] RebaseStringViewTest.RelativeToOldBase
[       OK ] RebaseStringViewTest.RelativeToOldBase (0 ms)
[ RUN      ] RebaseStringViewTest.MiddleOfSuperstring
[       OK ] RebaseStringViewTest.MiddleOfSuperstring (0 ms)
[ RUN      ] RebaseStringViewTest.PrefixSuperstring
[       OK ] RebaseStringViewTest.PrefixSuperstring (0 ms)
[----------] 7 tests from RebaseStringViewTest (0 ms total)
[----------] Global test environment tear-down
[==========] 9 tests from 2 test suites ran. (315 ms total)
[  PASSED  ] 8 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] RebaseStringViewTest.EmptyStringsZeroOffset
```

**Comment by mithro** [comment]
```
./bazel-verible/bazel-out/k8-fastbuild/testlogs/common/text/token_info_test/test.log
--------------
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //common/text:token_info_test
-----------------------------------------------------------------------------
Running main() from gmock_main.cc
[==========] Running 26 tests from 5 test suites.
[----------] Global test environment set-up.
[----------] 2 tests from RebaseStringViewDeathTest
[ RUN      ] RebaseStringViewDeathTest.SubstringMismatch
[       OK ] RebaseStringViewDeathTest.SubstringMismatch (119 ms)
[ RUN      ] RebaseStringViewDeathTest.SubstringMismatch2
[       OK ] RebaseStringViewDeathTest.SubstringMismatch2 (115 ms)
[----------] 2 tests from RebaseStringViewDeathTest (234 ms total)
[----------] 12 tests from TokenInfoTest
[ RUN      ] TokenInfoTest.EnumTextConstruction
[       OK ] TokenInfoTest.EnumTextConstruction (0 ms)
[ RUN      ] TokenInfoTest.AdvanceText
[       OK ] TokenInfoTest.AdvanceText (0 ms)
[ RUN      ] TokenInfoTest.Equality
[       OK ] TokenInfoTest.Equality (0 ms)
[ RUN      ] TokenInfoTest.EOFEquality
[       OK ] TokenInfoTest.EOFEquality (0 ms)
[ RUN      ] TokenInfoTest.Inequality
[       OK ] TokenInfoTest.Inequality (0 ms)
[ RUN      ] TokenInfoTest.EquivalentWithoutLocation
[       OK ] TokenInfoTest.EquivalentWithoutLocation (0 ms)
[ RUN      ] TokenInfoTest.EquivalentEOF
[       OK ] TokenInfoTest.EquivalentEOF (0 ms)
[ RUN      ] TokenInfoTest.IsEOF
[       OK ] TokenInfoTest.IsEOF (0 ms)
[ RUN      ] TokenInfoTest.IsEOFAnyString
[       OK ] TokenInfoTest.IsEOFAnyString (0 ms)
[ RUN      ] TokenInfoTest.ToStringEOF
[       OK ] TokenInfoTest.ToStringEOF (0 ms)
[ RUN      ] TokenInfoTest.ToStringWithBase
[       OK ] TokenInfoTest.ToStringWithBase (0 ms)
[ RUN      ] TokenInfoTest.ToStringWithBaseAndTranslator
[       OK ] TokenInfoTest.ToStringWithBaseAndTranslator (0 ms)
[----------] 12 tests from TokenInfoTest (0 ms total)
[----------] 1 test from TokenWithContextTest
[ RUN      ] TokenWithContextTest.StreamOutput
[       OK ] TokenWithContextTest.StreamOutput (0 ms)
[----------] 1 test from TokenWithContextTest (0 ms total)
[----------] 7 tests from RebaseStringViewTest
[ RUN      ] RebaseStringViewTest.EmptyStringsZeroOffset
common/text/token_info_test.cc:176: Failure
Value of: BoundsEqual(text, substr)
  Actual: true
Expected: false
[  FAILED  ] RebaseStringViewTest.EmptyStringsZeroOffset (0 ms)
[ RUN      ] RebaseStringViewTest.IdenticalCopy
[       OK ] RebaseStringViewTest.IdenticalCopy (0 ms)
[ RUN      ] RebaseStringViewTest.NewSubstringNotAtFront
[       OK ] RebaseStringViewTest.NewSubstringNotAtFront (0 ms)
[ RUN      ] RebaseStringViewTest.UsingCharPointer
[       OK ] RebaseStringViewTest.UsingCharPointer (0 ms)
[ RUN      ] RebaseStringViewTest.RelativeToOldBase
[       OK ] RebaseStringViewTest.RelativeToOldBase (0 ms)
[ RUN      ] RebaseStringViewTest.MiddleOfSuperstring
[       OK ] RebaseStringViewTest.MiddleOfSuperstring (0 ms)
[ RUN      ] RebaseStringViewTest.PrefixSuperstring
[       OK ] RebaseStringViewTest.PrefixSuperstring (0 ms)
[----------] 7 tests from RebaseStringViewTest (0 ms total)
[----------] 4 tests from TokenInfoConcatenateTest
[ RUN      ] TokenInfoConcatenateTest.EmptyTokens
[       OK ] TokenInfoConcatenateTest.EmptyTokens (0 ms)
[ RUN      ] TokenInfoConcatenateTest.OneToken
[       OK ] TokenInfoConcatenateTest.OneToken (0 ms)
[ RUN      ] TokenInfoConcatenateTest.MultipleTokens
[       OK ] TokenInfoConcatenateTest.MultipleTokens (0 ms)
[ RUN      ] TokenInfoConcatenateTest.MultipleTokensWithEmptyString
[       OK ] TokenInfoConcatenateTest.MultipleTokensWithEmptyString (0 ms)
[----------] 4 tests from TokenInfoConcatenateTest (0 ms total)
[----------] Global test environment tear-down
[==========] 26 tests from 5 test suites ran. (235 ms total)
[  PASSED  ] 25 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] RebaseStringViewTest.EmptyStringsZeroOffset
 1 FAILED TEST
--------------
```

**Comment by mithro** [comment]
The same two tests are failing now for all travis versions.

**Comment by hzeller** [comment]
this is strangely not reproducible with a gcc-7 compiler on a workstation, so something different is there in travis (libc++?). Anyway, I have a workaround pending.

**Comment by hzeller** [comment]
FYI, in ca3fce403ab5bf2cf56795b747da718c2be2b3ca I made it possible to use good ol' C++11 again. So we can `s/c++17/c++11/` and maybe this also helps with older compilers on older systems.

**Pull request closed without merging**
