### PR TITLE
Build release inside docker containers.

### PR DESCRIPTION
**Pull request by mithro**
Supports;
 - Centos 6, 7 and 8
 - Ubuntu LTS version (Trusty 14.04, Xenial 16.04, Bionic 18.04)
 - Ubuntu latest version (Eoan 19.10)

Signed-off-by: Tim 'mithro' Ansell <me@mith.ro>

### CODE REVIEW

**Comment by mithro** [comment]
This pull request builds for binaries for Centos and Ubuntu.

See output at https://www.travis-ci.org/mithro/verible/builds/649319498 and https://github.com/mithro/verible/releases

**Comment by hzeller** [comment]
Cool, can you add the copyright headers in
 
Docker/docker-generate.sh
Docker/docker-run.sh
.github/travis/install.sh
.github/travis/script.sh
.github/travis/success.sh

**Comment by mithro** [comment]
Are you looking at an old change? The copyright headers are already there?

**Comment by hzeller** [comment]
Ah, the good old missing full-stop at the end of the sentence. Let me widen that check.

**Comment by mithro** [comment]
Full stops added.

**Comment by mithro** [comment]
Also fixed the tabs in `Docker/docker-run.sh`

**Comment by hzeller** [comment]
Thanks, looks good now!

**Comment by hzeller** [comment]
Sending for review to you on the pull request import.

**Pull request closed without merging**
