### PR TITLE
travis: Build for multiple old GCC versions.

### PR DESCRIPTION
**Pull request by mithro**
Signed-off-by: Tim 'mithro' Ansell <me@mith.ro>

### CODE REVIEW

**Comment by mithro** [comment]
Compiling with an older version of gcc doesn't seem to have had any effect;
```
[tansell@centos6 ~]$ tar -zxvf verible-v0.0-197-g855d768-linux-amd64-Ubuntu-14.04-trusty-gcc5.tar.gz
[tansell@centos6 ~]$ verible-v0.0-197-g855d768/bin/verilog_lint --help
verible-v0.0-197-g855d768/bin/verilog_lint: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by verible-v0.0-197-g855d768/bin/verilog_lint)
verible-v0.0-197-g855d768/bin/verilog_lint: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by verible-v0.0-197-g855d768/bin/verilog_lint)
verible-v0.0-197-g855d768/bin/verilog_lint: /lib64/libc.so.6: version `GLIBC_2.16' not found (required by verible-v0.0-197-g855d768/bin/verilog_lint)
verible-v0.0-197-g855d768/bin/verilog_lint: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by verible-v0.0-197-g855d768/bin/verilog_lint)
verible-v0.0-197-g855d768/bin/verilog_lint: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.17' not found (required by verible-v0.0-197-g855d768/bin/verilog_lint)
verible-v0.0-197-g855d768/bin/verilog_lint: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by verible-v0.0-197-g855d768/bin/verilog_lint)
verible-v0.0-197-g855d768/bin/verilog_lint: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by verible-v0.0-197-g855d768/bin/verilog_lint)
verible-v0.0-197-g855d768/bin/verilog_lint: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by verible-v0.0-197-g855d768/bin/verilog_lint)
verible-v0.0-197-g855d768/bin/verilog_lint: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.5' not found (required by verible-v0.0-197-g855d768/bin/verilog_lint)
[tansell@centos6 ~]$ 
```

**Comment by mithro** [comment]
gcc-9 version
```
[tansell@centos6 ~]$ verible-v0.0-197-g855d768/bin/verilog_lint --help
verible-v0.0-197-g855d768/bin/verilog_lint: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by verible-v0.0-197-g855d768/bin/verilog_lint)
verible-v0.0-197-g855d768/bin/verilog_lint: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by verible-v0.0-197-g855d768/bin/verilog_lint)
verible-v0.0-197-g855d768/bin/verilog_lint: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.17' not found (required by verible-v0.0-197-g855d768/bin/verilog_lint)
verible-v0.0-197-g855d768/bin/verilog_lint: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by verible-v0.0-197-g855d768/bin/verilog_lint)
verible-v0.0-197-g855d768/bin/verilog_lint: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by verible-v0.0-197-g855d768/bin/verilog_lint)
verible-v0.0-197-g855d768/bin/verilog_lint: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by verible-v0.0-197-g855d768/bin/verilog_lint)
verible-v0.0-197-g855d768/bin/verilog_lint: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.5' not found (required by verible-v0.0-197-g855d768/bin/verilog_lint)
verible-v0.0-197-g855d768/bin/verilog_lint: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by verible-v0.0-197-g855d768/bin/verilog_lint)
verible-v0.0-197-g855d768/bin/verilog_lint: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by verible-v0.0-197-g855d768/bin/verilog_lint)
verible-v0.0-197-g855d768/bin/verilog_lint: /lib64/libc.so.6: version `GLIBC_2.16' not found (required by verible-v0.0-197-g855d768/bin/verilog_lint)
```

**Comment by mithro** [comment]
Looks like centos6 has
```
Running Transaction
  Installing : ppl-0.10.2-11.el6.x86_64                                                                        1/9 
  Installing : cloog-ppl-0.15.7-1.2.el6.x86_64                                                                 2/9 
  Installing : mpfr-2.4.1-6.el6.x86_64                                                                         3/9 
  Installing : cpp-4.4.7-23.el6.x86_64                                                                         4/9 
  Installing : libgomp-4.4.7-23.el6.x86_64                                                                     5/9 
  Installing : kernel-headers-2.6.32-754.27.1.el6.x86_64                                                       6/9 
  Installing : glibc-headers-2.12-1.212.el6_10.3.x86_64                                                        7/9 
  Installing : glibc-devel-2.12-1.212.el6_10.3.x86_64                                                          8/9 
  Installing : gcc-4.4.7-23.el6.x86_64                                                                         9/9 
```

**Comment by hzeller** [comment]
Is it possible to not choose the compiler version in the travis build, but use whatever default there is ?

Apparently we catch problems with choosing a different compiler as the libstdc++ will not match.

**Comment by mithro** [comment]
I'm going to go a difference approach here. Closing this pull request.

**Pull request closed without merging**
